### ISSUE TITLE
Importing sharp breaks the font

### ISSUE THREAD

**Issue by Glutch** [bostrom/text-to-image#108]
If you import the sharp image library, text-to-image "fontFamily" stops working and gives error
`Fontconfig error: Cannot load default config file: No such file: (null)`
in console.

Not sure how to fix or work around

```js
const textToImage = require('text-to-image')
const sharp = require('sharp')
```

**Comment by bostrom** [comment]
Thanks for the report. Can you create a codesandbox to showcase the issue?

**Comment by Glutch** [comment]
> Thanks for the report. Can you create a codesandbox to showcase the issue?

I've never done that, it should be easy to replicate though. However, i installed the library text2png instead which does the same thing as text-to-image. And the exact same thing happened there after requiring sharp. So it might be an issue with sharp

**Comment by bostrom** [comment]
Ok, thanks for letting me know!
