### ISSUE TITLE
Alignment issue with multiple space to format as table. 

### ISSUE THREAD

**Issue by imdkbj** [bostrom/text-to-image#11]
Hi, Pls check this is not looking good when i have used spaces to show my strings as table.

This is what looking on terminal.
![image](https://user-images.githubusercontent.com/46839821/74323275-488a7000-4dab-11ea-9f38-312c6fdb9e06.png)

This is what image i got.
![image](https://user-images.githubusercontent.com/46839821/74323351-648e1180-4dab-11ea-9d8f-322a522dddd2.png)

So seems spaces are being altered.

**Comment by bostrom** [comment]
It's because the font in the image is not a fixed-width font like in the terminal. So different characters have different width and that's why the pipe characters end up in different places. 

Try setting the fontFamily to "consolas" or "courier".

**Comment by imdkbj** [comment]
Thnx buddy!! U knocked the right bell.
