### ISSUE TITLE
Canvas error

### ISSUE THREAD

**Issue by alexandrsimply** [bostrom/text-to-image#113]
Hi. Trying to use this package but got some canvas error. Have some ideas for fixing it?

![Selection_022](https://user-images.githubusercontent.com/77664064/108972681-ff971800-769c-11eb-8a97-c47c5b419e75.png)
![Selection_023](https://user-images.githubusercontent.com/77664064/108972687-00c84500-769d-11eb-956a-75bea7e28cdf.png)
![Selection_024](https://user-images.githubusercontent.com/77664064/108972691-0160db80-769d-11eb-88f6-9398d2b1a910.png)

**Comment by bostrom** [comment]
@alexandrsimply did you figure it out?

**Comment by alexandrsimply** [comment]
Hi @bostrom. Yes, I had a problem with the docker image I changed it from node:12-alpine to node:14. Thank you.
