### ISSUE TITLE
\t doesn't work 

### ISSUE THREAD

**Issue by sarahs3** [bostrom/text-to-image#142]
Hi ^^

It's me again ^^ 

The \t doesn't work to make tabulation in the text.  (On the other hand, the \n works perfecly).

Can we make a tabulation with another way ? 

thank you in advance for your time :)

**Comment by bostrom** [comment]
Hi @sarahs3,

Thanks for your suggestion. How would you expect the \t to work? Should it just move the cursor forward x amount of pixels (code editor mode), or do you expect to have defined tab stops to get a kind of text alignment in an arbitrary position (document editing mode)? 

For the latter it would require to define tab stops separately and it comes with its own complexity. For the former, would it be enough just to add more whitespace characters?

**Comment by sarahs3** [comment]
Hi, 

Actually I got this result :
![sanstab](https://user-images.githubusercontent.com/82849954/118292524-02a1e780-b4d9-11eb-91a5-2381f0e5cf75.png)

And I want this (this image is edited with paint ^^) :
![avectab](https://user-images.githubusercontent.com/82849954/118292515-ffa6f700-b4d8-11eb-860f-43b8d595c7aa.png)

When I just try to add space characters in my string, they are ignored and I have the result that I have in my first image.

Thank you again for your time :)

**Comment by bostrom** [comment]
Hm, maybe I’m stripping leading white space... 🧐

I’ll try to take a look when I have time.

**Comment by sarahs3** [comment]
thank you :)

**Comment by sam-lex** [comment]
I have no idea how to fix it and what's causing it, but as I was about to give an example of what I tried.. it happens in here as well.. so it seems to be html related ..
`'                    test'`
`'.                   test'`
When you see my `test` above, it appears to have 1 space only between it, but it actually has 10+ white-spaces, both in the first and second one (between the period `.` and `t`).
I've tried doing `&nbsp;&nbsp;`.. but it just prints out as it is `&nbsp;` :(
