### ISSUE TITLE
Duplicate text issue

### ISSUE THREAD

**Issue by cedricsandars** [bostrom/text-to-image#156]
@bostrom - While applying bgColor as transparent and also setting customHeight, the texts are repeated twice. 

![output](https://user-images.githubusercontent.com/2046221/126049905-6dc2f429-25a7-4cb9-b304-e77d5edd5f09.jpg)

Passing the following in the config

customHeight: 900,
verticalAlign: 'center',
bgColor: "transparent",

**Comment by vumail159951** [comment]
Try this :
bgColor: "rgba(0, 0, 0, 0)",
textAlign: 'center'
