### ISSUE TITLE
Module not found : Can't resolve fs

### ISSUE THREAD

**Issue by Vishnu-rkumar** [bostrom/text-to-image#161]
keep showing this error in typescript

**Comment by bostrom** [comment]
Thanks for the report. Can you provide a working example (codesandbox) of
the issue? That would speed up the process.

**Comment by madmacc** [comment]
Similar error
Module not found: Error: Can't resolve 'path' in 'R:\hivepass\HivePassAdminApp\node_modules\text-to-image\dist'
