### ISSUE TITLE
Add Custom image path support

### ISSUE THREAD

**Issue by ycfay** [bostrom/text-to-image#188]
if debug mode,Can you add save custom of  picture path ?

Thanks

**Comment by bostrom** [comment]
Probably doable. I’ll look into it. 👍🏻

**Comment by ycfay** [comment]
thanks。
Wish you a Happy New Year!

**Comment by bostrom** [comment]
You’re welcome. I have a few things to fix before releasing it properly. In
the meantime, can you try it out and see if it works for you?

**Comment by ycfay** [comment]
Hi,firend,i find a new problem,If  Chinese character,will overflow the image.

for example:冰雪经济又被叫做白色经济，它是指利用冰雪开展相关旅游项目和运动项目，逐渐形成一条经济链。伴随着2022年冬奥会热度以及国家政策的大力支持，我国冰雪产业已经驶入快车道。2019年，我国冰雪产业市场规模已经突破5000亿元。

![This is an image](https://i.ibb.co/5hYvLVj/20220119-T081535196-Z.png)

**Comment by bostrom** [comment]
I don't know how Chinese works, but you don't seem to have any normal spaces? That's how this library breaks the lines, so without space characters, you're basically going to get one long line like you see in your example. 

Maybe you can educate me as of how Chinese should be line-wrapped?

**Comment by ycfay** [comment]
> I don't know how Chinese works, but you don't seem to have any normal spaces? That's how this library breaks the lines, so without space characters, you're basically going to get one long line like you see in your example.
> 
> Maybe you can educate me as of how Chinese should be line-wrapped?

:) thanks you reply.
Chinese characters don‘t need spaces，I'm trying.
I think need to calc the length of characters. If exceeds, we need to add  be a line-wrapped。

**Comment by bostrom** [comment]
@ycfay let's continue the discussion in #193
