### ISSUE TITLE
Error in /node_modules/text-to-image@5.1.1/dist/textToImage.js

### ISSUE THREAD

**Issue by GIT18195644** [bostrom/text-to-image#235]
Hi, 
I am new to text-to-image. I installed text to image 5.1.1 version. but there is error come from textToImage.js. The error is:

Error in /node_modules/text-to-image@5.1.1/dist/textToImage.js (8:45)
(0 , util_1.promisify) is not a function

How to resolve that? Please help me.

**Comment by bostrom** [comment]
Please install the latest version (currently 5.2.0) and try again. Reopen this if it's still an issue.

**Comment by Heesel** [comment]
I have the same issue. My current version is **5.2.0** 
![image](https://user-images.githubusercontent.com/49622357/194963112-0596d7fe-dbfc-4ec2-8396-bc04c6c86986.png)

**Comment by bostrom** [comment]
Continued in #252
