### ISSUE TITLE
Library issue on AWS EC2 instance

### ISSUE THREAD

**Issue by tarook1994** [bostrom/text-to-image#24]
I deployed my nodejs server on AWS EC2. The issue seems to be with the font configuration as the text in the images is represented as squares. I thought it might be an encoding issue however, the issue happens with English and Arabic characters. Is there anything that needs to configured in order to guarantee that the library works as expected?

**Comment by geeschmidt** [comment]
Also seeing this in Amazon Linux. Logs report this error:

Fontconfig error: Cannot load default config file

Sample ouput:

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAABMCAYAAABDNOEsAAAABmJLR0QA/wD/AP+gvaeTAAABfUlEQVR4nO3dO27DMBRFQTHw/rfMVG4M/95pDAkzbW7hJjqAAIpr770PABj6+/UPAOCcBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgOQ2Ga+13v79/lUUu+c7gCsZBeQ4Xj8MHx+ids93AFfhFRYAiYAAkAgIAImAAJAICACJgACQCAgAiYAAkAgIAMn4JPq3J6vtAK5tbR9qAiDwCguAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgGR0odSnS5PuV4vY2U12wDmNbyR89U//+LCws5vsgPPxCguAREAASAQEgERAAEgEBIBEQABIBASAREAASAQEgGR8Ev3bE8R2dpMdcD5r+yARAIFXWAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkAiIAAkAgJAIiAAJAICQCIgACQCAkDyDwtfltsAjiHHAAAAAElFTkSuQmCC`

![image](https://user-images.githubusercontent.com/3810978/77695475-d300ea80-6f79-11ea-88cc-8166fc93242c.png)

**Comment by tarook1994** [comment]
Hello geeschmidt! I figured it out. The issue is with the EC2 instance itself. You need to manually install the fonts on the machine in order to work correctly as the library depends on the system fonts. You might use 
$ sudo yum install fonts-arabic
