### ISSUE TITLE
Optional config is not optional

### ISSUE THREAD

**Issue by revjtanton** [bostrom/text-to-image#242]
**Version of the library**
5.2.0

**Describe the bug**
While the type declaration shows each element is optional, the `GenerateOptions` config itself is still _required_.

**To Reproduce**
Link to codesandbox.io or a snippet that will showcase the issue. Use [this sandbox](https://codesandbox.io/s/text-to-image-example-r8h1o?file=/src/index.ts) as base.
I'm not doing all of that. The error comes from writing something like this in TS: `this.#signatureImage = await textToImage.generate(this.signature)`

**Expected behavior**
No error

**Screenshots**
![Screen Shot 2022-07-08 at 5 39 25 PM](https://user-images.githubusercontent.com/6391564/178073842-e2084203-f25a-4c80-bbf5-8e616a570e5b.png)

**Additional context**

**Comment by bostrom** [comment]
This has been fixed in master and will be published in the next release.

**Comment by bostrom** [comment]
This is fixed in 6.0.0 which was released a few days back.
