### ISSUE TITLE
Enhanced Version with Latest Node.js Support and Updated Dependencies

### ISSUE THREAD

**Issue by Pnlvfx** [bostrom/text-to-image#274]
Hi everyone,

I'm excited to announce that I've created an updated version of this package, called text-to-image-2, which addresses several issues and introduces significant improvements.

Key Improvements:

  1. Updated dependencies: All dependencies have been upgraded to their latest versions, ensuring compatibility with modern environments.
  2. Node.js compatibility: This version now works flawlessly with the latest Node.js versions, resolving previous build issues.
  3. Performance enhancements: Various optimizations have been made to improve image generation performance.

To install it via npm, simply run:

``` npm install text-to-image-2 ```

I hope this updated version will be helpful to the community. Any feedback or suggestions for further improvements are greatly appreciated!

Best regards

**Comment by bostrom** [comment]
@Pnlvfx thanks for taking matters in your own hands! Sadly I don't have time to maintain this small library on the side of my day job, family, and hobbies that have been introduced into my life after I created text-to-image. 

I'm happy to see that there's still interest in this library, even though I regrettably can't spend much time on it. If you would like to become collaborator on this project, or take full ownership of it, I'd be happy to pass on the baton. I think that would be the most user friendly approach to keeping the library's users happy :) 

Let me know what you think! 

Br, 
Fred

**Comment by Pnlvfx** [comment]
Hi Fred,

Thank you so much for your thoughtful response and for considering me to take over the project! I truly appreciate your maturity and willingness to hand over something you’ve built, especially considering the new priorities in your life. It speaks volumes about your dedication to the community and to ensuring that the library continues to thrive.

I would be honored to maintain the project, keep it updated, and address any issues that arise. I’ll do my best to uphold the quality of the library and ensure its users remain happy.

Please let me know how we can move forward with the transition, and I’m excited to take on this responsibility.

Thanks again!

**Comment by bostrom** [comment]
Sounds great! I invited you as a collaborator. What would be the best way to reach you for a 1-on-1 discussion about the project?
