### ISSUE TITLE
Alignment option

### ISSUE THREAD

**Issue by cedricsandars** [bostrom/text-to-image#9]
Do you have any plan to add align text to left, center or right as an option? Any advice would be much appreciated.

**Comment by bostrom** [comment]
Hi and thanks for reaching out.

I don’t actively use this library myself any longer so new features are
brought in on a per PR or request basis.

Feel free to submit a PR for alignment! Otherwise I can try to find time to
add it, but don’t hold your breath 😉

**Comment by bostrom** [comment]
Added in https://github.com/bostrom/text-to-image/commit/a395105a930b04088ecfc302030c74c9bef27249
